spring:
  zipkin:
    base-url: http://zipkin:9411
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka

server:
  port: 8081
  datasource:
    password: postgres
    url: jdbc:postgresql://postgres:5433/login
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    password: ''
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ''

openapi:
  service:
    title: authenticator doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://gateway:8222 #api gateway url
springdoc:
  api-docs:
    path: /authenticator/v3/api-docs
  swagger-ui:
    path: /authenticator/swagger-ui.html

management:
  tracing:
    sampling:
      probability: 1.0