eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/schools
    username: postgres
    password: Pa55word
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8222/api/students

management:
  tracing:
    sampling:
      probability: 1.0

openapi:
  service:
    title: schools doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8222 #api gateway url
springdoc:
  api-docs:
    path: /schools/v3/api-docs
  swagger-ui:
    path: /schools/swagger-ui.html
