eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: Pa55word
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    schools-url: http://localhost:8070/api/schools

management:
  tracing:
    sampling:
      probability: 1.0


openapi:
  service:
    title: students doc #title that you will want to display in the swagger ui
    version: 1.0.0
    url: http://localhost:8222 #api gateway url
springdoc:
  api-docs:
    path: /students/v3/api-docs
  swagger-ui:
    path: /students/swagger-ui.html
